### ISSUE TITLE
RIPEMD160 listed as legacy

### ISSUE THREAD

**Issue by ysangkok** [bungle/lua-resty-nettle#1]
AFAIK there are no known RIPEMD160 weaknesses. Why is it listed as legacy?

**Comment by bungle** [comment]
Because the documentation (work in progress) follows Nettle's documentation: http://www.lysator.liu.se/~nisse/nettle/nettle.html#Legacy-hash-functions

Legacy doesn't neccessarely mean "weak". Just that there are better replacements that you should use instead.
