### ISSUE TITLE
segfault when using luajit GC64

### ISSUE THREAD

**Issue by craveica** [bungle/lua-resty-nettle#16]
cat t.lua
```
local base64 = require 'resty.nettle.base64'

local x = [[
1vfWu0C4L-v3PWIuQJTk4yt96LUplH7t8EIWo7cP1
2M21UAVchFADwRrbD4E42PsDssma9JKQdt1mKFVhN
LCaNI3AzkMq80Pw4h625XrMveaYOdZNONXS52WIX
]]

local function a(s)
   return base64.encode(s)
end

for i = 1,1 do
    print(a('a'))
end
```
luajit t.lua
```
YQ==
Segmentation fault
```

Latest luajit v2.1 and lua-resty-nettle  HEAD versions.

Only happens when luajit is running in GC64 mode.

**Comment by bungle** [comment]
I think this is possible a bug with GC64. I won't put too much effort on this until GC64 is stabilized.

**Comment by craveica** [comment]
It looks like ffi.cdefs are incompatible with my libnettle (3.4) causing invalid memory writes.

**Comment by bungle** [comment]
@craveica, can you point to them?

**Comment by bungle** [comment]
@craveica are they only incompatible when using GC64?

**Comment by bungle** [comment]
(and yes, it looks like they have changed since).

**Comment by bungle** [comment]
@craveica on latest HEAD, I updated `base64``cdef`s. Can you please try again, the example, and return back if it solved the problem. I will try to go through all the library to check that `cdef`s are up to date with `Nettle`.

See: https://github.com/bungle/lua-resty-nettle/commit/1ea8c8d4fa81ce99dc6eb49c1f0e0ba686a3309c

**Comment by craveica** [comment]
it may cause problems with GC32 too, however I didn't encounter any.

I've only updated base64.lua cdefs to match base64.h and it's working so far.

**Comment by bungle** [comment]
@craveica did you do it on your own, or did you try the one I did? If not, can you also confirm that my changes were ok as well? And if they were not, can you please submit yours?

**Comment by craveica** [comment]
My own. I just did the same changes, but only for cdefs. Haven't changed the lua code. I'll try yours.

**Comment by bungle** [comment]
@craveica thanks!

**Comment by craveica** [comment]
It's working nice. Thanks!

**Comment by bungle** [comment]
@craveica good to know, I will go through rest of the `cdef`s, but there are a lot of them so it will take time. Thanks for reporting!
