### ISSUE TITLE
Error 11 when trying to use rsa.sign()

### ISSUE THREAD

**Issue by chris-jansson** [bungle/lua-resty-nettle#19]
Hi, I'm trying to sign a message with SHA-256 but am running into an issue. First I create the digest:

    local sha2 = require "resty.nettle.sha2"
    local digest = hex(sha2.sha256(""))

And that produces the correct hash

    E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855

Then I try to sign it with the rsa module:

    local rsa = require "resty.nettle.rsa"
    rsa = rsa.new(public_key, private_key)
    local signature, err = rsa:sign(digest)

The output just says `make: *** [test] Error 11` and I'm not sure where to go from here.

I did look at the `.sign()` function for `rsa.lua` and it looks like the function assumes the signature based on the length of the digest. SHA-256 is chosen if the digest length is 32, but the digest is actually 64 characters long. Does this have anything to do with it?

I just started using this module so I'm guessing there's a simple fix and I'm just doing things wrong. Thanks in advance!

**Comment by bungle** [comment]
You digest is actually 64 chars (bytes) long because you HEX-encode it. If you don't it will be 32 bytes (8 bit clean).

**Comment by bungle** [comment]
RSA signing out of e.g. JWK, such as:
https://tools.ietf.org/html/rfc7517#appendix-A.2

Will go like this:
```lua
  local alg = require "resty.nettle.sha2".sha256

  local err
  local pub
  local n = jwk.n
  local e = jwk.e

  if n then
    n, err = base64url.decode(n)
    if not n then
      return nil, "rsa modulus could not be base64 url decoded (" ..  err .. ")"
    end

    n, err = base16.encode(n)
    if not n then
      return nil, "rsa modulus could not be base16 encoded (" ..  err .. ")"
    end
  end

  if e then
    e, err = base64url.decode(e)
    if not n then
      return nil, "rsa exponent could not be base64 url decoded (" ..  err .. ")"
    end

    e, err = base16.encode(e)
    if not e then
      return nil, "rsa exponent could not be base16 encoded (" ..  err .. ")"
    end
  end

  if e and n then
    pub, err = rsa.key.public.new(n, e)
    if not pub then
      return nil, "rsa public key could not be prepared (" ..  err .. ")"
    end
  end

  local pri

  local d = jwk.d
  if not d then
    return nil, "rsa secret exponent was not specified"
  end

  local p = jwk.p
  if not p then
    return nil, "rsa factor p was not specified"
  end

  local q = jwk.q
  if not q then
    return nil, "rsa factor q was not specified"
  end

  local dp = jwk.dp
  local dq = jwk.dq
  local qi = jwk.qi

  d, err = base64url.decode(d)
  if not d then
    return nil, "rsa secret exponent could not be base64 url decoded (" ..  err .. ")"
  end

  d, err = base16.encode(d)
  if not d then
    return nil, "rsa secret exponent could not be base16 encoded (" ..  err .. ")"
  end

  p, err = base64url.decode(p)
  if not p then
    return nil, "rsa factor p could not be base64 url decoded (" ..  err .. ")"
  end

  p, err = base16.encode(p)
  if not p then
    return nil, "rsa factor p could not be base16 encoded (" ..  err .. ")"
  end

  q, err = base64url.decode(q)
  if not q then
    return nil, "rsa factor q could not be base64 url decoded (" ..  err .. ")"
  end

  q, err = base16.encode(q)
  if not q then
    return nil, "rsa factor q could not be base16 encoded (" ..  err .. ")"
  end

  if dp then
    dp, err = base64url.decode(dp)
    if not dp then
      return nil, "rsa factor dp could not be base64 url decoded (" ..  err .. ")"
    end

    dp, err = base16.encode(dp)
    if not dp then
      return nil, "rsa factor dp could not be base16 encoded (" ..  err .. ")"
    end
  end

  if dq then
    dq, err = base64url.decode(dq)
    if not dq then
      return nil, "rsa factor dq could not be base64 url decoded (" ..  err .. ")"
    end

    dq, err = base16.encode(dq)
    if not dq then
      return nil, "rsa factor dq could not be base16 encoded (" ..  err .. ")"
    end
  end

  if qi then
    qi, err = base64url.decode(qi)
    if not qi then
      return nil, "rsa factor qi could not be base64 url decoded (" ..  err .. ")"
    end

    qi, err = base16.encode(qi)
    if not qi then
      return nil, "rsa factor qi could not be base16 encoded (" ..  err .. ")"
    end
  end

  pri, err = rsa.key.private.new(d, p, q, dp, dq, qi)
  if not pri then
    return nil, "rsa private key could not be prepared (" ..  err .. ")"
  end

  local r
  r, err = rsa.new(nil, pri)
  if not r then
    return nil, err
  end

  local digest
  digest, err = alg(inp)
  if not digest then
    return nil, err
  end

  digest, err = r:sign(digest)
  if not digest then
    return err
  end

  digest, err = base16.decode(digest)
  if not digest then
    return nil, "unable to base16 decode signature (" .. err .. ")"
  end

  digest, err = base64url.encode(digest)
  if not digest then
    return nil, "unable to base64 url encode signature (" .. err .. ")"
  end

  return digest
```

**Comment by chris-jansson** [comment]
Thanks for the quick response. I have a public and private key pair already, so I tried to condense the code you shared. I am still getting `Error 11`, though. Here's what I have now:

    local alg = require "resty.nettle.sha2".sha256
    local rsa = require "resty.nettle.rsa"
    local err

    local pri = [[-----BEGIN ENCRYPTED PRIVATE KEY-----
            <private key contents>
    -----END ENCRYPTED PRIVATE KEY-----]]

    local inp = ""

    local r
    r, err = rsa.new(nil, pri)
    if not r then
        return nil, err
    end

    local digest
    digest, err = alg(inp)
    if not digest then
        return nil, err
    end

    digest, err = r:sign(digest)
    if not digest then
        return err
    end

    digest, err = base16.decode(digest)
    if not digest then
        return nil, "unable to base16 decode signature (" .. err .. ")"
    end

    digest, err = base64url.encode(digest)
    if not digest then
        return nil, "unable to base64 url encode signature (" .. err .. ")"
    end

    return digest

**Comment by bungle** [comment]
You cannot use `PEM`. Try first with just `rsa.new()` and then sign. Then there is `rsa.keypair.new(n, e, r, p, seed)`, and also `rsa.key.private.new(d, p, q, a, b, c, base)` and `rsa.key.public.new(n, e, base)`.

Contributions are welcomed to add `PEM` support.

**Comment by bungle** [comment]
There is also `rsa.keypair.der(data)`. So if you can convert your `PEM` to `DER` you could use that.

```lua
local keypair = rsa.keypair.der("<binary-der>")
local r = rsa.new(keypair.public, keypair.private)
...
```

**Comment by chris-jansson** [comment]
Ah, that's good to know. I converted my private key `.pem` file to a `.der` with `openssl-rsa`. 

I tried to use `rsa.keypair.der(data)` like you suggested, but am getting the error message 

    unable to generate RSA keypair from DER

Here's where I'm at:

    local der = [[<binary data>]]
    local keypair, err = rsa.keypair.der(der)
    print(keypair)
    print(err)
    
When I open my private key `.der` file in vi, the data is definitely binary but it's split across 6 lines.. should it all be on one line? Or is multi-line ok?

**Comment by bungle** [comment]
Have you tried:
```lua
local f = assert(io.open("myfile.der", "rb"))
local der = f:read("*a")
f:close()
local keypair, err = rsa.keypair.der(der)
```

**Comment by bungle** [comment]
Small example:

```
openssl genrsa -des3 -out private.pem 2048
openssl rsa -in private.pem -out private.der -outform DER
```

```lua
rsa = require "resty.nettle.rsa"
f = assert(io.open("private.der", "rb"))
der = f:read("*a")
f:close()
keypair = rsa.keypair.der(der)  
r = rsa.new(keypair.public, keypair.private)
sha = require "resty.nettle.sha2"
digest = sha.sha256("sign me")
print(r:sign(digest))
```

**Comment by chris-jansson** [comment]
Aha. That did the trick. Thanks very much for your help!
