### ISSUE TITLE
ffi.string output for HMAC doesn't appear to be a string

### ISSUE THREAD

**Issue by cheezeburgerzdeluxe** [bungle/lua-resty-nettle#2]
Hi,

I am testing lua-resty-nettle for HMAC computations to verify signed cookies and I cannot get the output for the digest to be a readable string.

I am computing the digest like this:

`local digest = hmac("sha256", key, data)`

The return value is something like:

`2016/01/29 20:05:03 [error] 269#0: *120 [lua] access_by_lua(nginx.conf:65):13: Digest: (o)???k?K??
                                                                                                  ?Sݼx<?SՁ??/.
?`

I manually used the cookie values and key to compute the HMAC to verify the data and key.

**Comment by cheezeburgerzdeluxe** [comment]
I found the issue. I had to convert the returned data to hex using lua-resty-string.

**Comment by bungle** [comment]
In nettle there is also base16 (= hex) and base64 functions.
