### ISSUE TITLE
Error When I Use It On CentOS OpenResty

### ISSUE THREAD

**Issue by AndyWangG** [bungle/lua-resty-nettle#20]
It works on ubuntu os , but when I use it on centos/openresty  it dosen't work
/usr/local/openresty/luajit/bin/luajit: ./resty/nettle/des.lua:33: attempt to index local 'lib' (a boolean value)
stack traceback:
	./resty/nettle/des.lua:33: in main chunk
	[C]: in function 'require'
	a.lua:2: in main chunk
	[C]: at 0x004051d0
Can you help me !

**Comment by bungle** [comment]
@AndyWangG,

Have you installed `nettle` to your system? And if yes, what version? I remember CentOS 6/7 coming with `2.7` which is a way too old. At least for CentOS 6 there is this: https://centos.pkgs.org/6/epel-x86_64/nettle-3.2-2.el6.x86_64.rpm.html

**Comment by bungle** [comment]
Sometimes you also need to add ldconfig entries by running:
```
sudo ldconfig
````
But e.g. with CentOS you also need to create a file inside /etc/ld.so.conf.d/, e.g. local-x86_64.conf with following content:

```
/usr/local/lib64
```

and after that run:

```
sudo ldconfig
```

**Comment by AndyWangG** [comment]
Thank You  !!!!!
I have install nettle ，It works well!!!!
