### ISSUE TITLE
loop or previous error loading module 'resty.nettle.hmac'

### ISSUE THREAD

**Issue by NoKeqi** [bungle/lua-resty-nettle#21]
hello bungle

i tried to use this ,but errors occur:
loop or previous error loading module 'resty.nettle.hmac'

this is my test code:
local hmac = require ("resty.nettle.hmac")
local hash = hmac.sha256.new("a")
hash:update("a")
local dgst = hash:digest()
print("hmac sha256", #dgst, hex(dgst))

first i put nettle.lua and nettle directory in my default openresty directory (/usr/local/openresty/lualib/resty/)
second type "opm get bungle/lua-resty-nettle" in commond line
and it installed successfully

my lua version is 5.1.4

and i tried to use your other lib(lua-resty-session), it works correctly

now what can i do to solve the problem? help me~~~

**Comment by bungle** [comment]
Have you installed `libnettle`?
https://www.lysator.liu.se/~nisse/nettle/

**Comment by NoKeqi** [comment]
i had solved the problem
its not your problem
but mine due to my coding environment

thx~
