### ISSUE TITLE
Bug in loading the module

### ISSUE THREAD

**Issue by Tieske** [bungle/lua-resty-nettle#22]
This line: https://github.com/bungle/lua-resty-nettle/blob/master/lib/resty/nettle/library.lua#L60

Will trigger another error (indexing a nil value) somewhere else. The reason is that the module ends with a `return L()` in case of the error on line 60 this becomes `return nil, "error message"`.

If you `require` this module, `require` will only evaluate the `nil`, conclude it didn't get a return value and hence return a boolean `true`. Now when the client tries to access it's result of `require("resty.nettle.library")` it will get an unexpected error trying to index the boolean value.

**Comment by ibmsun1** [comment]
I got the same problem

**Comment by wangdafang** [comment]
I got the same problem, and  I tried to solve this problem in your way, but got a new problem :unable to load nettle ,have you ever seen this problem?

**Comment by Tieske** [comment]
my PR does not solve the problem, but it shows the proper underlying error. The problem remains in loading the module

**Comment by bungle** [comment]
You need to have `libnettle`, perhaps `libhogweed`, and `libgmp`. For Nettle you need to have `>=3.4` as of `1.0` release of this library. So closing this.
