### ISSUE TITLE
Segmentation fault in "resty.nettle.base64".encode in ubuntu server 18.04 LTS

### ISSUE THREAD

**Issue by xiangnanscu** [bungle/lua-resty-nettle#25]
Hello, bungle, I know this issue:#16 . Just here to report more info.
this problem doesn't exist in ubuntu server 14.04. It seems a system related problem.

**Comment by xiangnanscu** [comment]
terminal info when start the openresty:
```
nginx: [alert] lua_code_cache is off; this will hurt performance in ./conf/dev.conf:13
Segmentation fault
```

**Comment by xiangnanscu** [comment]
wait. also nginx version is `1.15.8.1`. other version is OK. so it seems both related to openresty and ubuntu.

**Comment by bungle** [comment]
@xiangnanscu I just updated the bindings to version `1.0`, can you check if this issue still exists?

**Comment by bungle** [comment]
OpenResty `1.15.8.1` enables GC64 by default.

**Comment by bungle** [comment]
I am 99% sure this is fixed now, so I will close this. @xiangnanscu please reopen if you still have any problems with it. I went through all the code and cdefs and updated them to latest. It is advisable to use Nettle at least `3.4`, I am not going to support older ones at this point.
