### ISSUE TITLE
Nettle 6/7/8 support

### ISSUE THREAD

**Issue by LoganDark** [bungle/lua-resty-nettle#36]
The latest versions of Ubuntu only support `libnettle6`, `libnettle7`, and `libnettle8` - not Nettle 3.

libnettle6 is 18.04-only,  
libnettle7 is 20.04-only,  
libnettle8 is 22.04-only.

It would be nice if this library could be updated to support the newer versions of Nettle.

**Comment by bungle** [comment]
@LoganDark, you can check older versions of this lib, they should be compatible with older nettle.

**Comment by LoganDark** [comment]
> @LoganDark, you can check older versions of this lib, they should be compatible with older nettle.

That's my point, older versions of nettle are no longer available, this library is 5 major versions out of date.

**Comment by LoganDark** [comment]
I only wanted to use Nettle for password hashing and I decided to make [my own bindings to Argon2](https://github.com/LoganDark/luajit-argon2) instead.

Since it doesn't look like this old Lua library is going to be updated, I'm going to close this issue. Feel free to reopen it if you actually do have plans to support modern versions of Nettle.
