### ISSUE TITLE
how to place libnettle.so

### ISSUE THREAD

**Issue by angelandy** [bungle/lua-resty-nettle#4]
@bungle hi, i have get an error : [error] 29778#0: *5 lua entry thread aborted: runtime error: libnettle.so: cannot open shared obje    ct file: No such file or directory

how to fix it?
i already put libnettle.so in /usr/local/openresty/lualib/
wrong path?

**Comment by bungle** [comment]
Place it in your Operating System's library path, e.g. `/usr/local/lib`. See LuaJIT documentation for more information. `/usr/local/openresty/lualib/` is a wrong path. That path is for Lua C API wrappers. I'm sure running something like `make install` for nettle will do the right thing automatically. But you may place it manually if you want. Using your OS package manager to install nettle will also do the correct thing.

**Comment by angelandy** [comment]
@bungle, hi bungle，thank you for answer me.

I had put it into /usr/local/lib.
but i also get the same issue.

I can see there are libnettle.so in that folder before. because i remember i have make install before

root@andy-ubuntu:/usr/local/lib# ls -a
.  ..  libnettle.a  libnettle.so  libnettle.so.6  libnettle.so.6.2  libnettle.so.bak  pkgconfig  python2.7  python3.4  site_ruby

version
nettle: nettle-3.2
openresty: openresty-1.9.7.3
lua:5.1

any Suggestions?

**Comment by angelandy** [comment]
@bungle ,
 Hi bungle, i have fix it by myself.

 everything run well after I have run the command "ldconfig"

thank you.

**Comment by bungle** [comment]
Great! I will close it then.
