### ISSUE TITLE
Version mismatch on Debian Jessie, libnettle4 incompatible (not a bug)

### ISSUE THREAD

**Issue by russmac** [bungle/lua-resty-nettle#7]
I appear to get this error due to a version mismatch with Debian Jessie ancient version of libnettle4 - 2.75 and this library. I can see Ubuntu Xenial LTS has the new libraries which would be a workaround.

```
lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/resty/nettle/sha2.lua:74: /usr/lib/x86_64-linux-gnu/libnettle.so: undefined symbol: nettle_sha512_224_init
```

Looking at the nettle source it seems the solution is nettle 3.2 , I was wondering though is there a specific commit I could checkout at to be able to use libnettle4 (2.7) for now?

```
[russmac@fusioncore debug]$ grep -RH sha512_224 nettle-2.7/ |wc -l
0
[russmac@fusioncore debug]$ grep -RH sha512_224 nettle-3.2/ |wc -l
41
```

**Comment by bungle** [comment]
How about building latest from the sources and put it in /usr/local? I'm not sure how much the nettle abi has changed from 2.x to 3.x. Do you have some special algoritm in mind? It seems sha512_224 is missing from 2.7.

**Comment by russmac** [comment]
Thank you for the advice, I ended up not needing to sha any more.
