### ISSUE TITLE
loop or previous error loading module ?

### ISSUE THREAD

**Issue by liwmj** [bungle/lua-resty-nettle#9]
*9 lua entry thread aborted: runtime error: ./lua/test.lua:51: loop or previous error loading module 'resty.nettle.aes'

Before this, I use the:
```
local package_path = package.path
package.path = string.format("%s;%s?.lua;%s?/init.lua", package_path, p, p)
```
Other libraries can be found, and normal operation, only to use `lua-resty-nettle` will appear this problem, is this why?

**Comment by bungle** [comment]
Could you show me the full code. I don't know about those `p` things there.

**Comment by bungle** [comment]
I will close this now, as I have not got any futher details. @liwangmj if you still feel there is problems in this library, please reopen this.
